# Generated by Django 3.1.5 on 2021-01-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AlterField(
            model_name='shelf',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номенр полки'),
        ),
        migrations.CreateModel(
            name='BookOnShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция на полке')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.shelf')),
            ],
        ),
    ]
