# Generated by Django 3.1.5 on 2021-01-23 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_auto_20210123_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookonshelf",
            name="book",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
                verbose_name="Книга",
            ),
            preserve_default=False,
        ),
    ]
