# Generated by Django 3.1.5 on 2021-01-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210123_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookonshelf',
            name='book',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга'),
        ),
    ]
